services:
  postgres:
    image: postgres:16-alpine
    container_name: monefyi-planner-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - planner_pg_data:/var/lib/postgresql/data

volumes:
  planner_pg_data:
