import type { LucideIcon } from 'lucide-react';
import {
  AlertTriangle,
  BadgePercent,
  Building,
  Building2,
  Calendar,
  Camera,
  Car,
  CheckCircle,
  ChevronDown,
  Circle,
  FilePlus,
  FileText,
  FlaskConical,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  HardHat,
  Home,
  Laptop,
  Lightbulb,
  MapPin,
  Megaphone,
  Package,
  Palette,
  PiggyBank,
  Shield,
  Sparkles,
  Store,
  TrendingUp,
  Truck,
  Users,
  UsersRound,
  Warehouse,
  Wrench,
  Zap,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  'alert-triangle': AlertTriangle,
  'badge-percent': BadgePercent,
  building: Building,
  'building-2': Building2,
  calendar: Calendar,
  camera: Camera,
  car: Car,
  'check-circle': CheckCircle,
  'chevron-down': ChevronDown,
  circle: Circle,
  'file-plus': FilePlus,
  'file-text': FileText,
  'flask-conical': FlaskConical,
  gift: Gift,
  globe: Globe,
  'graduation-cap': GraduationCap,
  hammer: Hammer,
  'hard-hat': HardHat,
  home: Home,
  laptop: Laptop,
  lightbulb: Lightbulb,
  'map-pin': MapPin,
  megaphone: Megaphone,
  package: Package,
  palette: Palette,
  'piggy-bank': PiggyBank,
  shield: Shield,
  sparkles: Sparkles,
  store: Store,
  'trending-up': TrendingUp,
  truck: Truck,
  users: Users,
  'users-round': UsersRound,
  warehouse: Warehouse,
  wrench: Wrench,
  zap: Zap,
};

export function resolveBudgetIcon(key: string): LucideIcon {
  return ICONS[key] || Circle;
}
