import { emptyBillingConfig } from '../estimationBillingConfig';
import { defaultPdfSettings } from '../../services/pdfSettingsService';
import type { EstimationFormDraft, PdfTemplate } from '../../types/estimator';
import type { PdfSettings } from '../../types/pdfSettings';

export function previewEstimationDraft(template: PdfTemplate): EstimationFormDraft {
  return {
    code: 'PWR-2026-001',
    title: 'Renovasi Kamar Mandi 2x3',
    customer_name: 'Andi Wijaya',
    customer_phone: '08123456789',
    customer_address: 'Jl. Sudirman No. 123, Bandung',
    project_id: null,
    overhead_pct: 0,
    margin_pct: 20,
    discount_pct: 0,
    discount_amount: 0,
    adjustments: [],
    tax_pct: 11,
    notes: 'Material premium sesuai spek terlampir.',
    terms_conditions: 'DP 50% saat approval\nPelunasan H+1 selesai\nJam kerja 08.00-17.00',
    validity_days: 14,
    status: 'penawaran',
    pdf_template: template,
    pdf_invoice_template: template,
    pdf_primary_color: '',
    pdf_secondary_color: '',
    pdf_show_images: false,
    pdf_show_bank: true,
    pdf_show_signature: true,
    pdf_show_logo: true,
    pdf_show_stamp: true,
    pdf_show_footer: true,
    images: [],
    billing_config: {
      ...emptyBillingConfig(50),
      payments: [{
        id: 'pay-1',
        milestone_key: 'dp',
        date: '2026-01-10',
        amount: 3_000_000,
        payment_method: 'Transfer BCA',
      }],
    },
    items: [
      {
        name: 'Bongkar keramik lama',
        category: 'upah',
        unit: 'm²',
        qty: 6,
        hpp_per_unit: 300_000,
        margin_pct: 38,
        selling_price_per_unit: 415_000,
        item_discount_pct: 0,
        item_discount_amount: 0,
        is_bonus: false,
        included: true,
        total_hpp: 1_800_000,
        total_selling: 2_490_000,
        total_profit: 690_000,
        sort_order: 0,
        notes: '',
      },
      {
        name: 'Keramik premium',
        category: 'material',
        unit: 'm²',
        qty: 8,
        hpp_per_unit: 250_000,
        margin_pct: 40,
        selling_price_per_unit: 350_000,
        item_discount_pct: 0,
        item_discount_amount: 0,
        is_bonus: false,
        included: true,
        total_hpp: 2_000_000,
        total_selling: 2_800_000,
        total_profit: 800_000,
        sort_order: 1,
        notes: '',
      },
      {
        name: 'Instalasi & finishing',
        category: 'jasa',
        unit: 'ls',
        qty: 1,
        hpp_per_unit: 1_200_000,
        margin_pct: 50,
        selling_price_per_unit: 1_800_000,
        item_discount_pct: 0,
        item_discount_amount: 0,
        is_bonus: false,
        included: true,
        total_hpp: 1_200_000,
        total_selling: 1_800_000,
        total_profit: 600_000,
        sort_order: 2,
        notes: '',
      },
    ],
  };
}

export function previewPdfSettings(partial: Partial<PdfSettings> & { org_id?: string }): PdfSettings {
  const defaults = defaultPdfSettings(partial.org_id || 'preview', 'Contoh Konstruksi');
  return {
    ...defaults,
    ...partial,
    id: partial.id || 'preview',
    created_at: partial.created_at || new Date().toISOString(),
    updated_at: partial.updated_at || new Date().toISOString(),
    company_name: partial.company_name || 'Contoh Konstruksi',
    company_tagline: partial.company_tagline || 'Kontraktor Terpercaya',
    address: partial.address || 'Jl. Asia Afrika No. 8, Bandung',
    phone: partial.phone || '022-1234567',
    email: partial.email || 'halo@contoh.com',
    signature_name: partial.signature_name || 'Budi Santoso',
    signature_title: partial.signature_title || 'Direktur',
    bank_name: partial.bank_name || 'BCA',
    bank_account: partial.bank_account || '1234567890',
    bank_account_name: partial.bank_account_name || 'Contoh Konstruksi',
  };
}
