import type { Content, TDocumentDefinitions } from 'pdfmake/interfaces';
import { buildImageSection, type QuotationPdfContext } from './quotationPdfContext';

function itemsTable(ctx: QuotationPdfContext, headerFill: string, altFill?: string): Content {
  const body: Content[][] = [
    [
      { text: '#', style: 'tableHeader', fillColor: headerFill },
      { text: 'Item', style: 'tableHeader', fillColor: headerFill },
      { text: 'Qty', style: 'tableHeader', fillColor: headerFill },
      { text: 'Satuan', style: 'tableHeader', fillColor: headerFill },
      { text: 'Harga/Unit', style: 'tableHeader', fillColor: headerFill, alignment: 'right' },
      { text: 'Total', style: 'tableHeader', fillColor: headerFill, alignment: 'right' },
    ],
    ...ctx.items.map((row, i) => [
      { text: String(row.no), fillColor: altFill && i % 2 ? altFill : undefined } as Content,
      row.name,
      { text: row.qty, alignment: 'center' } as Content,
      row.unit,
      { text: row.unitPrice, alignment: 'right' } as Content,
      { text: row.total, alignment: 'right', bold: true } as Content,
    ] as Content[]),
  ];

  return {
    table: { headerRows: 1, widths: [22, '*', 32, 40, 70, 75], body },
    layout: {
      hLineWidth: () => 0.5,
      vLineWidth: () => 0,
      hLineColor: () => '#e2e8f0',
      paddingLeft: () => 6,
      paddingRight: () => 6,
      paddingTop: () => 4,
      paddingBottom: () => 4,
    },
    margin: [0, 8, 0, 8] as [number, number, number, number],
  };
}

function summaryBlock(ctx: QuotationPdfContext, highlightColor: string): Content {
  const rows: Content[] = [
    { columns: [{ text: 'Subtotal', width: '*' }, { text: ctx.subtotalLabel, width: 'auto', alignment: 'right' }], margin: [0, 2, 0, 2] as [number, number, number, number] },
  ];
  if (ctx.overheadLabel) rows.push({ columns: [{ text: 'Overhead', width: '*' }, { text: ctx.overheadLabel, width: 'auto', alignment: 'right' }], margin: [0, 2, 0, 2] as [number, number, number, number] });
  if (ctx.discountLabel) rows.push({ columns: [{ text: 'Diskon', width: '*' }, { text: ctx.discountLabel, width: 'auto', alignment: 'right', color: '#e11d48' }], margin: [0, 2, 0, 2] as [number, number, number, number] });
  if (ctx.taxLabel) rows.push({ columns: [{ text: 'PPN', width: '*' }, { text: ctx.taxLabel, width: 'auto', alignment: 'right' }], margin: [0, 2, 0, 2] as [number, number, number, number] });

  rows.push({
    table: {
      widths: ['*'],
      body: [[{
        stack: [
          { text: 'GRAND TOTAL', fontSize: 9, color: '#ffffff', opacity: 0.9 },
          { text: ctx.grandTotal, fontSize: 18, bold: true, color: '#ffffff' },
          { text: `(${ctx.grandTotalWords} rupiah)`, fontSize: 8, color: '#ffffff', italics: true, margin: [0, 4, 0, 0] as [number, number, number, number] },
        ],
        fillColor: highlightColor,
        margin: 8,
      }]],
    },
    layout: 'noBorders',
    margin: [0, 8, 0, 0] as [number, number, number, number],
  });

  return { stack: rows, alignment: 'right' };
}

function termsAndClosing(ctx: QuotationPdfContext): Content[] {
  const blocks: Content[] = [];

  if (ctx.termsLines.length) {
    blocks.push(
      { text: 'SYARAT & KETENTUAN', style: 'sectionTitle', margin: [0, 16, 0, 6] as [number, number, number, number] },
      { ul: ctx.termsLines, fontSize: 9, margin: [0, 0, 0, 12] as [number, number, number, number] },
    );
  }

  if (ctx.options.showBank && ctx.bankName) {
    blocks.push(
      { text: 'INFORMASI PEMBAYARAN', style: 'sectionTitle', margin: [0, 0, 0, 6] as [number, number, number, number] },
      {
        text: [
          `Bank: ${ctx.bankName}\n`,
          `No. Rek: ${ctx.bankAccount}\n`,
          `a/n: ${ctx.bankAccountName}`,
        ],
        fontSize: 9,
        margin: [0, 0, 0, 12] as [number, number, number, number],
      },
    );
  }

  if (ctx.options.showSignature) {
    const sigStack: Content[] = [{ text: 'Hormat kami,', fontSize: 9, margin: [0, 8, 0, 8] as [number, number, number, number] }];
    if (ctx.signatureDataUri) {
      sigStack.push({ image: ctx.signatureDataUri, width: 100, margin: [0, 0, 0, 4] as [number, number, number, number] });
    } else {
      sigStack.push({ text: '\n\n', margin: [0, 20, 0, 0] as [number, number, number, number] });
    }
    if (ctx.signatureName) sigStack.push({ text: ctx.signatureName, bold: true, fontSize: 10 });
    if (ctx.signatureTitle) sigStack.push({ text: ctx.signatureTitle, fontSize: 9, color: '#64748b' });
    blocks.push({ stack: sigStack });
  }

  blocks.push({
    text: `${ctx.footerText} · Generated by Monefyi ${new Date().getFullYear()}`,
    fontSize: 7,
    color: '#94a3b8',
    alignment: 'center',
    margin: [0, 20, 0, 0] as [number, number, number, number],
  });

  return blocks;
}

function baseStyles(ctx: QuotationPdfContext) {
  return {
    docTitle: { fontSize: 22, bold: true, color: ctx.colors.primary },
    sectionTitle: { fontSize: 11, bold: true, color: ctx.colors.secondary },
    tableHeader: { bold: true, fontSize: 9, color: '#ffffff' },
    label: { fontSize: 8, color: '#64748b', margin: [0, 0, 0, 2] as [number, number, number, number] },
    value: { fontSize: 10, color: ctx.colors.secondary },
  };
}

function modernDoc(ctx: QuotationPdfContext): TDocumentDefinitions {
  const imgSection = buildImageSection(ctx, 'modern');
  const headerLeft: Content[] = [];
  if (ctx.logoDataUri) headerLeft.push({ image: ctx.logoDataUri, width: 60, margin: [0, 0, 0, 4] as [number, number, number, number] });
  headerLeft.push({ text: ctx.companyName, fontSize: 12, bold: true, color: '#ffffff' });
  if (ctx.companyTagline) headerLeft.push({ text: ctx.companyTagline, fontSize: 8, color: '#e0e7ff' });

  return {
    pageSize: 'A4',
    pageMargins: [40, 40, 40, 40],
    defaultStyle: { font: 'Roboto', fontSize: 10 },
    styles: baseStyles(ctx),
    content: [
      {
        table: {
          widths: ['*', 'auto'],
          body: [[
            { stack: headerLeft, fillColor: ctx.colors.primary, margin: 12 },
            {
              stack: [
                { text: 'QUOTATION', fontSize: 10, color: '#e0e7ff', alignment: 'right' },
                { text: ctx.code, fontSize: 16, bold: true, color: '#ffffff', alignment: 'right' },
              ],
              fillColor: ctx.colors.primary,
              margin: 12,
            },
          ]],
        },
        layout: 'noBorders',
        margin: [0, 0, 0, 16] as [number, number, number, number],
      },
      {
        table: {
          widths: ['*', '*'],
          body: [[
            {
              stack: [
                { text: 'DARI', style: 'label' },
                { text: ctx.companyName, bold: true },
                { text: [ctx.companyAddress, ctx.companyPhone, ctx.companyEmail].filter(Boolean).join('\n'), fontSize: 9 },
              ],
              fillColor: '#f8fafc',
              margin: 10,
            },
            {
              stack: [
                { text: 'UNTUK', style: 'label' },
                { text: ctx.customerName, bold: true },
                { text: [ctx.customerPhone, ctx.customerAddress].filter(Boolean).join('\n'), fontSize: 9 },
              ],
              fillColor: '#f8fafc',
              margin: 10,
            },
          ]],
        },
        layout: 'noBorders',
        margin: [0, 0, 0, 12] as [number, number, number, number],
      },
      { text: `Proyek: ${ctx.title}`, bold: true, margin: [0, 0, 0, 4] as [number, number, number, number] },
      { text: `Tanggal: ${ctx.dateLabel}  ·  Berlaku: ${ctx.validLabel}`, fontSize: 9, color: '#64748b', margin: [0, 0, 0, 8] as [number, number, number, number] },
      ...(imgSection ? [imgSection] : []),
      { text: 'RINCIAN PENAWARAN', style: 'sectionTitle', pageBreak: imgSection ? undefined : undefined },
      itemsTable(ctx, ctx.colors.primary, '#f8fafc'),
      summaryBlock(ctx, ctx.colors.primary),
      ...(ctx.notes ? [{ text: `Catatan: ${ctx.notes}`, fontSize: 9, italics: true, margin: [0, 8, 0, 0] as [number, number, number, number] }] : []),
      ...termsAndClosing(ctx),
    ],
  };
}

function classicDoc(ctx: QuotationPdfContext): TDocumentDefinitions {
  const imgSection = buildImageSection(ctx, 'classic');
  return {
    pageSize: 'A4',
    pageMargins: [50, 50, 50, 50],
    defaultStyle: { font: 'Roboto', fontSize: 10 },
    styles: baseStyles(ctx),
    content: [
      {
        columns: [
          ctx.logoDataUri ? { image: ctx.logoDataUri, width: 50 } : { text: '' },
          {
            width: '*',
            stack: [
              { text: ctx.companyName, fontSize: 14, bold: true },
              { text: ctx.companyAddress, fontSize: 9 },
            ],
            margin: [10, 0, 0, 0] as [number, number, number, number],
          },
        ],
        margin: [0, 0, 0, 8] as [number, number, number, number],
      },
      { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 495, y2: 0, lineWidth: 1, lineColor: ctx.colors.secondary }] },
      {
        columns: [
          { width: '*', stack: [{ text: 'Penawaran', fontSize: 18, bold: true, margin: [0, 12, 0, 0] as [number, number, number, number] }, { text: ctx.code, fontSize: 11 }] },
          {
            width: 180,
            stack: [
              { text: 'Kepada:', bold: true, margin: [0, 12, 0, 4] as [number, number, number, number] },
              ctx.customerName,
              { text: ctx.customerAddress, fontSize: 9 },
              ctx.customerPhone,
            ],
          },
        ],
        margin: [0, 0, 0, 12] as [number, number, number, number],
      },
      { text: ctx.title, bold: true },
      { text: `${ctx.dateLabel} · Berlaku ${ctx.validLabel}`, fontSize: 9, color: '#64748b', margin: [0, 4, 0, 12] as [number, number, number, number] },
      itemsTable(ctx, ctx.colors.secondary, '#fafafa'),
      summaryBlock(ctx, ctx.colors.secondary),
      ...(imgSection ? [imgSection] : []),
      ...termsAndClosing(ctx),
    ],
  };
}

function minimalDoc(ctx: QuotationPdfContext): TDocumentDefinitions {
  const imgSection = buildImageSection(ctx, 'minimal');
  return {
    pageSize: 'A4',
    pageMargins: [60, 60, 60, 60],
    defaultStyle: { font: 'Roboto', fontSize: 10, color: '#334155' },
    styles: baseStyles(ctx),
    content: [
      { text: ctx.companyName, fontSize: 11, margin: [0, 0, 0, 2] as [number, number, number, number] },
      { text: ctx.code, fontSize: 9, color: '#94a3b8', margin: [0, 0, 0, 24] as [number, number, number, number] },
      { text: ctx.title, fontSize: 20, bold: true, margin: [0, 0, 0, 8] as [number, number, number, number] },
      { text: `Untuk ${ctx.customerName}`, fontSize: 10, margin: [0, 0, 0, 4] as [number, number, number, number] },
      { text: `${ctx.dateLabel} · ${ctx.validLabel}`, fontSize: 9, color: '#94a3b8', margin: [0, 0, 0, 20] as [number, number, number, number] },
      ...(imgSection ? [imgSection] : []),
      {
        table: {
          headerRows: 1,
          widths: [20, '*', 35, 40, 65, 70],
          body: [
            ['#', 'Item', 'Qty', 'Unit', 'Harga', 'Total'],
            ...ctx.items.map(r => [
              String(r.no),
              r.name,
              r.qty,
              r.unit,
              { text: r.unitPrice, alignment: 'right' as const },
              { text: r.total, alignment: 'right' as const },
            ]),
          ],
        },
        layout: 'noBorders' as const,
        margin: [0, 16, 0, 16] as [number, number, number, number],
      } as Content,
      summaryBlock(ctx, ctx.colors.primary),
      ...termsAndClosing(ctx),
    ],
  };
}

function boldDoc(ctx: QuotationPdfContext): TDocumentDefinitions {
  const imgSection = buildImageSection(ctx, 'bold');
  return {
    pageSize: 'A4',
    pageMargins: [40, 40, 40, 40],
    defaultStyle: { font: 'Roboto', fontSize: 10 },
    styles: baseStyles(ctx),
    content: [
      {
        stack: [
          { text: ctx.companyName, fontSize: 20, bold: true, color: '#ffffff' },
          { text: 'PENAWARAN HARGA', fontSize: 10, color: '#e0e7ff' },
          { text: ctx.code, fontSize: 14, bold: true, color: '#ffffff', margin: [0, 4, 0, 0] as [number, number, number, number] },
        ],
        fillColor: ctx.colors.primary,
        margin: 16,
      },
      { text: ctx.title, fontSize: 16, bold: true, margin: [0, 16, 0, 4] as [number, number, number, number] },
      { text: `${ctx.customerName} · ${ctx.dateLabel}`, fontSize: 9, margin: [0, 0, 0, 12] as [number, number, number, number] },
      ...(imgSection ? [{ ...(imgSection as object), pageBreak: 'before' as const } as Content] : []),
      itemsTable(ctx, ctx.colors.secondary, '#f1f5f9'),
      summaryBlock(ctx, ctx.colors.primary),
      {
        table: {
          widths: ['*'],
          body: [[{
            text: 'Setuju? Hubungi kami sekarang untuk konfirmasi penawaran ini.',
            bold: true,
            color: '#ffffff',
            alignment: 'center',
            margin: 10,
            fillColor: ctx.colors.accent,
          }]],
        },
        layout: 'noBorders',
        margin: [0, 12, 0, 0] as [number, number, number, number],
      },
      ...termsAndClosing(ctx),
    ],
  };
}

export function buildDocumentDefinition(ctx: QuotationPdfContext): TDocumentDefinitions {
  switch (ctx.template) {
    case 'classic': return classicDoc(ctx);
    case 'minimal': return minimalDoc(ctx);
    case 'bold': return boldDoc(ctx);
    default: return modernDoc(ctx);
  }
}
